# -*- coding: utf-8 -*-
"""Week4_daily1_Ch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19yxYtJnJWt8N9j_dLOo1M7cxyqyxQjUt

Apolo BARNABAS
Week4_daily1_Ch

Quizz 1....

What is a class? = A class is a blueprint or template used to create objects. It defines the attributes (variables) and methods (functions) that the objects will have.

What is an instance? =/ An instance is an actual object created from a class.

What is encapsulation? =/ Encapsulation is the idea of bundling data and methods together inside a class and restricting direct access to some data.

What is abstraction? =/ Abstraction means hiding complex implementation details and showing only the essential features.

What is inheritance? =/ Inheritance allows one class to inherit attributes and methods from another class.

What is multiple inheritance? =/ Multiple inheritance means a class inherits from more than one parent class. What is polymorphism? =/ Polymorphism means “many forms.”

What is method resolution order or MRO? =/ MRO is the order Python follows to search for methods in inheritance hierarchies, especially with multiple inheritance.
"""

import random


class Card:
    def __init__(self, suit, value):
        self.suit = suit
        self.value = value

    def __str__(self):
        return f"{self.value} of {self.suit}"

    def __repr__(self):
        return self.__str__()


class Deck:
    suits = ["Hearts", "Diamonds", "Clubs", "Spades"]
    values = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "10",
              "J", "Q", "K"]

    def __init__(self):
        self.cards = []
        self.shuffle()

    def shuffle(self):
        """Create a complete deck of 52 cards and shuffle it."""
        self.cards = [
            Card(suit, value)
            for suit in self.suits
            for value in self.values
        ]
        random.shuffle(self.cards)

    def deal(self):
        """Deal one card and remove it from the deck."""
        if len(self.cards) == 0:
            return "No cards left in the deck."
        return self.cards.pop()


#The testing
deck = Deck()

print(f"Cards in deck: {len(deck.cards)}")

card1 = deck.deal()
print("Dealt:", card1)

card2 = deck.deal()
print("Dealt:", card2)

print(f"Cards remaining: {len(deck.cards)}")